// Writes CLAUDE.md and AGENTS.md from docs/AGENTS.src.md. Lines between START_CLAUDE and END_CLAUDE go only into
// CLAUDE.md, lines between START_AGENTS and END_AGENTS only into AGENTS.md, and START_IGNORE blocks into neither.
// With --check it writes nothing and fails if either file differs from what it would write, which catches both a
// forgotten regeneration and a hand edit to a generated file.
//
// Usage: node scripts/build-agent-instructions.ts [--check]

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const SOURCE = 'docs/AGENTS.src.md';
const HEADER = `<!-- AUTOGENERATED FILE, DO NOT EDIT DIRECTLY -->
<!-- To regenerate, run \`npm run agent-docs\` -->
<!-- Source content: ${SOURCE} -->

`;

const TARGETS = { CLAUDE: 'CLAUDE.md', AGENTS: 'AGENTS.md' } as const;
type Target = keyof typeof TARGETS;
type Block = Target | 'IGNORE';
const BLOCKS: readonly Block[] = ['CLAUDE', 'AGENTS', 'IGNORE'];

interface SourceLine {
    text: string;
    block: Block | undefined;
}

const isCheckOnly = process.argv.includes('--check');
const lines = parse(await readFile(path.join(ROOT, SOURCE), 'utf8'));
const outputs = (['CLAUDE', 'AGENTS'] as const).map((target) => ({
    file: TARGETS[target],
    content: render(lines, target),
}));

if (isCheckOnly) {
    const current = await Promise.all(outputs.map(async ({ file }) => readIfPresent(path.join(ROOT, file))));
    const stale = outputs.filter(({ content }, index) => current[index] !== content).map(({ file }) => file);
    if (stale.length > 0) {
        console.error(`${stale.join(' and ')} do not match ${SOURCE}. Edit ${SOURCE}, then run npm run agent-docs.`);
        process.exitCode = 1;
    }
} else {
    await Promise.all(outputs.map(async ({ file, content }) => writeFile(path.join(ROOT, file), content)));
    console.log(`Wrote ${outputs.map(({ file }) => file).join(' and ')} from ${SOURCE}`);
}

/** Each line with the block it sits in. Marker lines are dropped, and a marker out of place is an error. */
function parse(source: string): SourceLine[] {
    const result: SourceLine[] = [];
    let open: { block: Block; lineNumber: number } | undefined;
    for (const [index, text] of source.split(/\r?\n/v).entries()) {
        const lineNumber = index + 1;
        const marker = text.trim();
        const start = BLOCKS.find((block) => marker === `START_${block}`);
        const end = BLOCKS.find((block) => marker === `END_${block}`);
        if (start !== undefined) {
            if (open !== undefined) {
                throw new Error(
                    `${SOURCE}:${String(lineNumber)}: START_${start} is inside START_${open.block} from line ${String(open.lineNumber)}; blocks do not nest`,
                );
            }
            open = { block: start, lineNumber };
        } else if (end === undefined) {
            result.push({ text, block: open?.block });
        } else {
            if (open?.block !== end) {
                throw new Error(`${SOURCE}:${String(lineNumber)}: END_${end} has no matching START_${end}`);
            }
            open = undefined;
        }
    }
    if (open !== undefined) {
        throw new Error(`${SOURCE}:${String(open.lineNumber)}: START_${open.block} is never closed`);
    }
    return result;
}

function render(source: readonly SourceLine[], target: Target): string {
    const body = source
        .filter(({ block }) => block === undefined || block === target)
        .map(({ text }) => text)
        .join('\n');
    // Dropped blocks leave runs of blank lines behind them.
    return HEADER + body.replaceAll(/\n{3,}/gv, '\n\n').replace(/^\n+/v, '');
}

/** The file's text, or an empty string if it does not exist yet, which never matches a rendered output. */
async function readIfPresent(file: string): Promise<string> {
    try {
        return await readFile(file, 'utf8');
    } catch {
        return '';
    }
}
