/// <reference lib="webworker" />
/// <reference types="@sveltejs/kit" />
import { build, files, version } from '$service-worker';

// The worker lib types `self` as a plain worker's scope; this is a service worker's.
declare const self: ServiceWorkerGlobalScope;

// name of the cache of the application's static assets,
// meaning all the bundler-generated files as well as
// everything in the `static` directory
const STATIC_ASSETS_CACHE_NAME = `cache${version}`;

// name of the cache for everything else
// only used when user is offline
const OFFLINE_CACHE_NAME = `offline${version}`;

// `build` is an array of all the files generated by the bundler
// `files` is an array of everything in the `static` directory
const staticAssets = new Set(build.concat(files));

const toCache = Array.from(staticAssets);

self.addEventListener('install', (event) => {
    event.waitUntil(cacheStaticAssets());
});

async function cacheStaticAssets(): Promise<void> {
    const cache = await caches.open(STATIC_ASSETS_CACHE_NAME);
    await cache.addAll(toCache);
    void self.skipWaiting();
}

self.addEventListener('activate', (event) => {
    event.waitUntil(deleteOldCaches());
});

/** Deletes every cache but the new static asset cache */
async function deleteOldCaches(): Promise<void> {
    const keys = await caches.keys();
    for (const key of keys) {
        if (key !== STATIC_ASSETS_CACHE_NAME) await caches.delete(key);
    }
    void self.clients.claim();
}

/**
 * Fetch asset from network and store in cache.
 * Fall back to cache if user is offline.
 */
async function fetchAndCache(request: Request): Promise<Response> {
    const cache = await caches.open(OFFLINE_CACHE_NAME);

    try {
        const response = await fetch(request);
        void cache.put(request, response.clone());
        return response;
    } catch (err) {
        const response = await cache.match(request);
        if (response) return response;
        throw err;
    }
}

self.addEventListener('fetch', (event) => {
    if (event.request.method !== 'GET' || event.request.headers.has('range')) return;

    const url = new URL(event.request.url);

    // don't try to handle non-http URIs such as `data:`
    const isHttp = url.protocol.startsWith('http');
    if (!isHttp) return;

    // don't try to handle requests when in development
    const isDevServerRequest = url.hostname === self.location.hostname && url.port !== self.location.port;
    if (isDevServerRequest) return;

    // is it one of the application's assets?
    const isStaticAsset = url.host === self.location.host && staticAssets.has(url.pathname);

    // is the request asking for it to not be cached?
    const skipBecauseUncached =
        !isStaticAsset && (event.request.cache === 'only-if-cached' || event.request.cache === 'no-store');
    if (skipBecauseUncached) return;

    // is it a request for an image that isn't one of the application's assets?
    const isImageRequest = !isStaticAsset && event.request.destination === 'image';
    if (!isImageRequest) return;

    event.respondWith(fetchAndCache(event.request));
});
